"use client";

import React, { useRef } from "react";
import { Printer, Download, X } from "lucide-react";

interface ReportPrintModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  subtitle?: string;
  dataSummary?: Array<{ label: string; value: string }>;
  children: React.ReactNode;
}

export default function ReportPrintModal({
  isOpen,
  onClose,
  title,
  subtitle,
  dataSummary,
  children
}: ReportPrintModalProps) {
  const printRef = useRef<HTMLDivElement>(null);

  if (!isOpen) return null;

  const now = new Date();
  const dateStr = now.toLocaleDateString('en-NG', { dateStyle: 'full' });
  const timeStr = now.toLocaleTimeString('en-NG', { timeStyle: 'short' });

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-slate-900/70 dark:bg-slate-950/85 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 w-full max-w-5xl h-[90vh] rounded-[2.5rem] flex flex-col shadow-2xl overflow-hidden">
        
        {/* Top Control Bar (Non-printable) */}
        <div className="print:hidden flex justify-between items-center px-6 py-4 border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-955 shrink-0">
          <div className="flex items-center gap-3">
            <img src="/k-1.png" alt="Kaya Logo" className="h-8 w-auto object-contain" />
            <div>
              <h2 className="font-extrabold text-sm text-slate-900 dark:text-white">{title}</h2>
              <p className="text-[10px] text-slate-400">PDF Report Export & Printable Document</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handlePrint}
              className="px-4 py-2 bg-kaya-orange hover:bg-orange-600 text-white font-bold text-xs rounded-xl shadow-md flex items-center gap-1.5 transition-all"
            >
              <Printer className="h-4 w-4" />
              <span>Print / Save as PDF</span>
            </button>

            <button
              onClick={onClose}
              className="p-2 rounded-xl text-slate-400 hover:text-slate-600 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-slate-800 transition-colors"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Printable Document Area */}
        <div className="flex-1 overflow-y-auto p-8 sm:p-12 space-y-8 bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100 font-sans print:p-0 print:overflow-visible print:bg-white print:text-black" ref={printRef}>
          
          {/* PDF Report Header */}
          <div className="border-b-2 border-slate-900 dark:border-white pb-6 flex justify-between items-start gap-6">
            <div className="space-y-2">
              <img src="/k-1.png" alt="Kaya Market Logo" className="h-12 w-auto object-contain mb-2 print:h-10" />
              <h1 className="text-2xl sm:text-3xl font-black tracking-tight text-slate-900 dark:text-white uppercase">{title}</h1>
              {subtitle && <p className="text-xs font-semibold text-slate-500 dark:text-slate-400">{subtitle}</p>}
            </div>

            <div className="text-right text-[11px] space-y-1 font-semibold text-slate-600 dark:text-slate-300">
              <div><strong className="text-slate-900 dark:text-white">Organization:</strong> KayaMarket Logistics Ltd</div>
              <div><strong className="text-slate-900 dark:text-white">Date Generated:</strong> {dateStr}</div>
              <div><strong className="text-slate-900 dark:text-white">Time Generated:</strong> {timeStr}</div>
              <div><strong className="text-slate-900 dark:text-white">Generated By:</strong> KayaMarket Admin Management Console</div>
            </div>
          </div>

          {/* Quick Summary Grid */}
          {dataSummary && dataSummary.length > 0 && (
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 bg-slate-50 dark:bg-slate-955 p-4 rounded-2xl border border-slate-200 dark:border-slate-800 print:bg-slate-100 print:border-slate-300 print:text-black">
              {dataSummary.map((item, idx) => (
                <div key={idx} className="space-y-0.5">
                  <span className="text-[10px] uppercase font-bold text-slate-400 print:text-slate-600">{item.label}</span>
                  <p className="text-sm font-black text-slate-900 dark:text-white print:text-black">{item.value}</p>
                </div>
              ))}
            </div>
          )}

          {/* Report Main Content */}
          <div className="space-y-6">
            {children}
          </div>

          {/* Footer & Page Counter */}
          <div className="pt-8 border-t border-slate-200 dark:border-slate-800 flex justify-between items-center text-[10px] text-slate-400 print:border-slate-300 print:text-slate-600">
            <span>KayaMarket Operations & Financial Reporting Platform © 2026</span>
            <span>Confidential Executive Document • Page 1 of 1</span>
          </div>

        </div>

      </div>
    </div>
  );
}
